package entcrypt

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
)

func TestWriteRegistry_GeneratesFormattedDeterministicFile(t *testing.T) {
	target := t.TempDir()
	g := &gen.Graph{
		Config: &gen.Config{
			Package: "example.com/project/ent",
			Target:  target,
		},
		Nodes: []*gen.Type{
			{
				Name: "User",
				Fields: []*gen.Field{
					encryptedStringField("phone"),
					encryptedStringField("email"),
					plainStringField("name"),
				},
			},
			{
				Name: "PaymentMethod",
				Fields: []*gen.Field{
					encryptedStringField("cardholder_name"),
					encryptedStringField("billing_zip"),
				},
			},
		},
	}

	if err := writeRegistry(g); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(target, "entcrypt_gen.go")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by entcrypt. DO NOT EDIT.
package ent

import "github.com/k0in/entcrypt"

func init() {
	entcrypt.Register("PaymentMethod", "billing_zip", "cardholder_name")
	entcrypt.Register("User", "email", "phone")
}
`
	if string(got) != want {
		t.Fatalf("generated registry mismatch:\n%s", got)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0644 {
		t.Fatalf("generated registry mode = %v, want 0644", got)
	}
}

func TestWriteRegistry_NoEncryptedFields(t *testing.T) {
	target := t.TempDir()
	g := &gen.Graph{
		Config: &gen.Config{
			Package: "example.com/project/ent",
			Target:  target,
		},
		Nodes: []*gen.Type{
			{
				Name: "User",
				Fields: []*gen.Field{
					plainStringField("name"),
				},
			},
		},
	}

	if err := writeRegistry(g); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(target, "entcrypt_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "// No encrypted fields found.") {
		t.Fatalf("generated registry should document empty registry:\n%s", got)
	}
}

func TestWriteRegistry_RejectsNonStringEncryptedField(t *testing.T) {
	g := &gen.Graph{
		Config: &gen.Config{
			Package: "example.com/project/ent",
			Target:  t.TempDir(),
		},
		Nodes: []*gen.Type{
			{
				Name: "User",
				Fields: []*gen.Field{
					{
						Name:        "age",
						Type:        &field.TypeInfo{Type: field.TypeInt},
						Annotations: gen.Annotations{EncryptedField{}.Name(): map[string]any{}},
					},
				},
			},
		},
	}

	err := writeRegistry(g)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "User.age") || !strings.Contains(err.Error(), "only string fields") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func encryptedStringField(name string) *gen.Field {
	f := plainStringField(name)
	f.Annotations = gen.Annotations{EncryptedField{}.Name(): map[string]any{}}
	return f
}

func plainStringField(name string) *gen.Field {
	return &gen.Field{
		Name: name,
		Type: &field.TypeInfo{Type: field.TypeString},
	}
}
