package entcrypt

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

type Extension struct{}

func (Extension) Hooks() []gen.Hook {
	return []gen.Hook{
		func(next gen.Generator) gen.Generator {
			return gen.GenerateFunc(func(g *gen.Graph) error {
				if err := next.Generate(g); err != nil {
					return err
				}
				return writeRegistry(g)
			})
		},
	}
}

func (Extension) Annotations() []entc.Annotation { return nil }
func (Extension) Templates() []*gen.Template { return nil }
func (Extension) Options() []entc.Option { return nil }

func writeRegistry(g *gen.Graph) error {
	var buf []byte
	buf = append(buf, []byte("// Code generated by entcrypt. DO NOT EDIT.\n")...)
	buf = append(buf, []byte("package "+filepath.Base(g.Package)+"\n\n")...)
	buf = append(buf, []byte("import \"github.com/k0in/entcrypt\"\n\n")...)
	buf = append(buf, []byte("func init() {\n")...)

	type entry struct {
		typ    string
		fields []string
	}
	var entries []entry

	for _, n := range g.Nodes {
		var fields []string
		for _, f := range n.Fields {
			if _, ok := f.Annotations["EncryptedField"]; ok {
				fields = append(fields, f.Name)
			}
		}
		if len(fields) > 0 {
			sort.Strings(fields)
			entries = append(entries, entry{typ: n.Name, fields: fields})
		}
	}

	if len(entries) == 0 {
		buf = append(buf, []byte("\t// No encrypted fields found.\n")...)
		buf = append(buf, []byte("}\n")...)
	} else {
		for _, e := range entries {
			buf = append(buf, []byte(fmt.Sprintf("\tentcrypt.Register(%q", e.typ))...)
			for _, f := range e.fields {
				buf = append(buf, []byte(fmt.Sprintf(", %q", f))...)
			}
			buf = append(buf, []byte(")\n")...)
		}
		buf = append(buf, []byte("}\n")...)
	}

	out := filepath.Join(g.Target, "entcrypt_gen.go")
	if err := os.MkdirAll(filepath.Dir(out), 0750); err != nil {
		return fmt.Errorf("entcrypt: %w", err)
	}
	if err := os.WriteFile(out, buf, 0600); err != nil {
		return fmt.Errorf("entcrypt: write %s: %w", out, err)
	}
	return nil
}