// Code generated by entcrypt. DO NOT EDIT.
package ent

import "github.com/k0in/entcrypt"

func init() {
	entcrypt.Register("PaymentMethod", "billing_zip", "cardholder_name")
	entcrypt.Register("User", "email", "phone")
}
