// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k0in/entcrypt/examples/complex/ent/paymentmethod"
	"github.com/k0in/entcrypt/examples/complex/ent/user"
)

// PaymentMethodCreate is the builder for creating a PaymentMethod entity.
type PaymentMethodCreate struct {
	config
	mutation *PaymentMethodMutation
	hooks    []Hook
}

// SetBrand sets the "brand" field.
func (_c *PaymentMethodCreate) SetBrand(v string) *PaymentMethodCreate {
	_c.mutation.SetBrand(v)
	return _c
}

// SetLastFour sets the "last_four" field.
func (_c *PaymentMethodCreate) SetLastFour(v string) *PaymentMethodCreate {
	_c.mutation.SetLastFour(v)
	return _c
}

// SetCardholderName sets the "cardholder_name" field.
func (_c *PaymentMethodCreate) SetCardholderName(v string) *PaymentMethodCreate {
	_c.mutation.SetCardholderName(v)
	return _c
}

// SetBillingZip sets the "billing_zip" field.
func (_c *PaymentMethodCreate) SetBillingZip(v string) *PaymentMethodCreate {
	_c.mutation.SetBillingZip(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *PaymentMethodCreate) SetOwnerID(id int) *PaymentMethodCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *PaymentMethodCreate) SetOwner(v *User) *PaymentMethodCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the PaymentMethodMutation object of the builder.
func (_c *PaymentMethodCreate) Mutation() *PaymentMethodMutation {
	return _c.mutation
}

// Save creates the PaymentMethod in the database.
func (_c *PaymentMethodCreate) Save(ctx context.Context) (*PaymentMethod, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentMethodCreate) SaveX(ctx context.Context) *PaymentMethod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentMethodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentMethodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentMethodCreate) check() error {
	if _, ok := _c.mutation.Brand(); !ok {
		return &ValidationError{Name: "brand", err: errors.New(`ent: missing required field "PaymentMethod.brand"`)}
	}
	if _, ok := _c.mutation.LastFour(); !ok {
		return &ValidationError{Name: "last_four", err: errors.New(`ent: missing required field "PaymentMethod.last_four"`)}
	}
	if _, ok := _c.mutation.CardholderName(); !ok {
		return &ValidationError{Name: "cardholder_name", err: errors.New(`ent: missing required field "PaymentMethod.cardholder_name"`)}
	}
	if _, ok := _c.mutation.BillingZip(); !ok {
		return &ValidationError{Name: "billing_zip", err: errors.New(`ent: missing required field "PaymentMethod.billing_zip"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "PaymentMethod.owner"`)}
	}
	return nil
}

func (_c *PaymentMethodCreate) sqlSave(ctx context.Context) (*PaymentMethod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentMethodCreate) createSpec() (*PaymentMethod, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentMethod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentmethod.Table, sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Brand(); ok {
		_spec.SetField(paymentmethod.FieldBrand, field.TypeString, value)
		_node.Brand = value
	}
	if value, ok := _c.mutation.LastFour(); ok {
		_spec.SetField(paymentmethod.FieldLastFour, field.TypeString, value)
		_node.LastFour = value
	}
	if value, ok := _c.mutation.CardholderName(); ok {
		_spec.SetField(paymentmethod.FieldCardholderName, field.TypeString, value)
		_node.CardholderName = value
	}
	if value, ok := _c.mutation.BillingZip(); ok {
		_spec.SetField(paymentmethod.FieldBillingZip, field.TypeString, value)
		_node.BillingZip = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.OwnerTable,
			Columns: []string{paymentmethod.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_payment_methods = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentMethodCreateBulk is the builder for creating many PaymentMethod entities in bulk.
type PaymentMethodCreateBulk struct {
	config
	err      error
	builders []*PaymentMethodCreate
}

// Save creates the PaymentMethod entities in the database.
func (_c *PaymentMethodCreateBulk) Save(ctx context.Context) ([]*PaymentMethod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentMethod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMethodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentMethodCreateBulk) SaveX(ctx context.Context) []*PaymentMethod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentMethodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentMethodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
