// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/k0in/entcrypt/examples/complex/ent/paymentmethod"
	"github.com/k0in/entcrypt/examples/complex/ent/user"
)

// PaymentMethod is the model entity for the PaymentMethod schema.
type PaymentMethod struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Brand holds the value of the "brand" field.
	Brand string `json:"brand,omitempty"`
	// LastFour holds the value of the "last_four" field.
	LastFour string `json:"last_four,omitempty"`
	// CardholderName holds the value of the "cardholder_name" field.
	CardholderName string `json:"cardholder_name,omitempty"`
	// BillingZip holds the value of the "billing_zip" field.
	BillingZip string `json:"billing_zip,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentMethodQuery when eager-loading is set.
	Edges                PaymentMethodEdges `json:"edges"`
	user_payment_methods *int
	selectValues         sql.SelectValues
}

// PaymentMethodEdges holds the relations/edges for other nodes in the graph.
type PaymentMethodEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentMethodEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentMethod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentmethod.FieldID:
			values[i] = new(sql.NullInt64)
		case paymentmethod.FieldBrand, paymentmethod.FieldLastFour, paymentmethod.FieldCardholderName, paymentmethod.FieldBillingZip:
			values[i] = new(sql.NullString)
		case paymentmethod.ForeignKeys[0]: // user_payment_methods
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentMethod fields.
func (_m *PaymentMethod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentmethod.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case paymentmethod.FieldBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand", values[i])
			} else if value.Valid {
				_m.Brand = value.String
			}
		case paymentmethod.FieldLastFour:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_four", values[i])
			} else if value.Valid {
				_m.LastFour = value.String
			}
		case paymentmethod.FieldCardholderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cardholder_name", values[i])
			} else if value.Valid {
				_m.CardholderName = value.String
			}
		case paymentmethod.FieldBillingZip:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_zip", values[i])
			} else if value.Valid {
				_m.BillingZip = value.String
			}
		case paymentmethod.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_payment_methods", value)
			} else if value.Valid {
				_m.user_payment_methods = new(int)
				*_m.user_payment_methods = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentMethod.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentMethod) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the PaymentMethod entity.
func (_m *PaymentMethod) QueryOwner() *UserQuery {
	return NewPaymentMethodClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this PaymentMethod.
// Note that you need to call PaymentMethod.Unwrap() before calling this method if this PaymentMethod
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentMethod) Update() *PaymentMethodUpdateOne {
	return NewPaymentMethodClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentMethod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentMethod) Unwrap() *PaymentMethod {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentMethod is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentMethod) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentMethod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("brand=")
	builder.WriteString(_m.Brand)
	builder.WriteString(", ")
	builder.WriteString("last_four=")
	builder.WriteString(_m.LastFour)
	builder.WriteString(", ")
	builder.WriteString("cardholder_name=")
	builder.WriteString(_m.CardholderName)
	builder.WriteString(", ")
	builder.WriteString("billing_zip=")
	builder.WriteString(_m.BillingZip)
	builder.WriteByte(')')
	return builder.String()
}

// PaymentMethods is a parsable slice of PaymentMethod.
type PaymentMethods []*PaymentMethod
