// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k0in/entcrypt/examples/complex/ent/paymentmethod"
	"github.com/k0in/entcrypt/examples/complex/ent/predicate"
	"github.com/k0in/entcrypt/examples/complex/ent/user"
)

// PaymentMethodUpdate is the builder for updating PaymentMethod entities.
type PaymentMethodUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMethodMutation
}

// Where appends a list predicates to the PaymentMethodUpdate builder.
func (_u *PaymentMethodUpdate) Where(ps ...predicate.PaymentMethod) *PaymentMethodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBrand sets the "brand" field.
func (_u *PaymentMethodUpdate) SetBrand(v string) *PaymentMethodUpdate {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableBrand(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetLastFour sets the "last_four" field.
func (_u *PaymentMethodUpdate) SetLastFour(v string) *PaymentMethodUpdate {
	_u.mutation.SetLastFour(v)
	return _u
}

// SetNillableLastFour sets the "last_four" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableLastFour(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetLastFour(*v)
	}
	return _u
}

// SetCardholderName sets the "cardholder_name" field.
func (_u *PaymentMethodUpdate) SetCardholderName(v string) *PaymentMethodUpdate {
	_u.mutation.SetCardholderName(v)
	return _u
}

// SetNillableCardholderName sets the "cardholder_name" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableCardholderName(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetCardholderName(*v)
	}
	return _u
}

// SetBillingZip sets the "billing_zip" field.
func (_u *PaymentMethodUpdate) SetBillingZip(v string) *PaymentMethodUpdate {
	_u.mutation.SetBillingZip(v)
	return _u
}

// SetNillableBillingZip sets the "billing_zip" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableBillingZip(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetBillingZip(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *PaymentMethodUpdate) SetOwnerID(id int) *PaymentMethodUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PaymentMethodUpdate) SetOwner(v *User) *PaymentMethodUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the PaymentMethodMutation object of the builder.
func (_u *PaymentMethodUpdate) Mutation() *PaymentMethodMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PaymentMethodUpdate) ClearOwner() *PaymentMethodUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentMethodUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentMethodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentMethodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentMethodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentMethodUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentMethod.owner"`)
	}
	return nil
}

func (_u *PaymentMethodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentmethod.Table, paymentmethod.Columns, sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(paymentmethod.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastFour(); ok {
		_spec.SetField(paymentmethod.FieldLastFour, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardholderName(); ok {
		_spec.SetField(paymentmethod.FieldCardholderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingZip(); ok {
		_spec.SetField(paymentmethod.FieldBillingZip, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.OwnerTable,
			Columns: []string{paymentmethod.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.OwnerTable,
			Columns: []string{paymentmethod.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentMethodUpdateOne is the builder for updating a single PaymentMethod entity.
type PaymentMethodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMethodMutation
}

// SetBrand sets the "brand" field.
func (_u *PaymentMethodUpdateOne) SetBrand(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableBrand(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetLastFour sets the "last_four" field.
func (_u *PaymentMethodUpdateOne) SetLastFour(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetLastFour(v)
	return _u
}

// SetNillableLastFour sets the "last_four" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableLastFour(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetLastFour(*v)
	}
	return _u
}

// SetCardholderName sets the "cardholder_name" field.
func (_u *PaymentMethodUpdateOne) SetCardholderName(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetCardholderName(v)
	return _u
}

// SetNillableCardholderName sets the "cardholder_name" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableCardholderName(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetCardholderName(*v)
	}
	return _u
}

// SetBillingZip sets the "billing_zip" field.
func (_u *PaymentMethodUpdateOne) SetBillingZip(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetBillingZip(v)
	return _u
}

// SetNillableBillingZip sets the "billing_zip" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableBillingZip(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetBillingZip(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *PaymentMethodUpdateOne) SetOwnerID(id int) *PaymentMethodUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PaymentMethodUpdateOne) SetOwner(v *User) *PaymentMethodUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the PaymentMethodMutation object of the builder.
func (_u *PaymentMethodUpdateOne) Mutation() *PaymentMethodMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PaymentMethodUpdateOne) ClearOwner() *PaymentMethodUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the PaymentMethodUpdate builder.
func (_u *PaymentMethodUpdateOne) Where(ps ...predicate.PaymentMethod) *PaymentMethodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentMethodUpdateOne) Select(field string, fields ...string) *PaymentMethodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentMethod entity.
func (_u *PaymentMethodUpdateOne) Save(ctx context.Context) (*PaymentMethod, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentMethodUpdateOne) SaveX(ctx context.Context) *PaymentMethod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentMethodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentMethodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentMethodUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentMethod.owner"`)
	}
	return nil
}

func (_u *PaymentMethodUpdateOne) sqlSave(ctx context.Context) (_node *PaymentMethod, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentmethod.Table, paymentmethod.Columns, sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentMethod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentmethod.FieldID)
		for _, f := range fields {
			if !paymentmethod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(paymentmethod.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastFour(); ok {
		_spec.SetField(paymentmethod.FieldLastFour, field.TypeString, value)
	}
	if value, ok := _u.mutation.CardholderName(); ok {
		_spec.SetField(paymentmethod.FieldCardholderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingZip(); ok {
		_spec.SetField(paymentmethod.FieldBillingZip, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.OwnerTable,
			Columns: []string{paymentmethod.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.OwnerTable,
			Columns: []string{paymentmethod.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentMethod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
