// Code generated by ent, DO NOT EDIT.

package paymentmethod

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentmethod type in the database.
	Label = "payment_method"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldLastFour holds the string denoting the last_four field in the database.
	FieldLastFour = "last_four"
	// FieldCardholderName holds the string denoting the cardholder_name field in the database.
	FieldCardholderName = "cardholder_name"
	// FieldBillingZip holds the string denoting the billing_zip field in the database.
	FieldBillingZip = "billing_zip"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the paymentmethod in the database.
	Table = "payment_methods"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "payment_methods"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_payment_methods"
)

// Columns holds all SQL columns for paymentmethod fields.
var Columns = []string{
	FieldID,
	FieldBrand,
	FieldLastFour,
	FieldCardholderName,
	FieldBillingZip,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "payment_methods"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_payment_methods",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PaymentMethod queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// ByLastFour orders the results by the last_four field.
func ByLastFour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFour, opts...).ToFunc()
}

// ByCardholderName orders the results by the cardholder_name field.
func ByCardholderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCardholderName, opts...).ToFunc()
}

// ByBillingZip orders the results by the billing_zip field.
func ByBillingZip(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingZip, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
