// Code generated by ent, DO NOT EDIT.

package paymentmethod

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/k0in/entcrypt/examples/complex/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLTE(FieldID, id))
}

// Brand applies equality check predicate on the "brand" field. It's identical to BrandEQ.
func Brand(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldBrand, v))
}

// LastFour applies equality check predicate on the "last_four" field. It's identical to LastFourEQ.
func LastFour(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldLastFour, v))
}

// CardholderName applies equality check predicate on the "cardholder_name" field. It's identical to CardholderNameEQ.
func CardholderName(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldCardholderName, v))
}

// BillingZip applies equality check predicate on the "billing_zip" field. It's identical to BillingZipEQ.
func BillingZip(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldBillingZip, v))
}

// BrandEQ applies the EQ predicate on the "brand" field.
func BrandEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldBrand, v))
}

// BrandNEQ applies the NEQ predicate on the "brand" field.
func BrandNEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNEQ(FieldBrand, v))
}

// BrandIn applies the In predicate on the "brand" field.
func BrandIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldIn(FieldBrand, vs...))
}

// BrandNotIn applies the NotIn predicate on the "brand" field.
func BrandNotIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNotIn(FieldBrand, vs...))
}

// BrandGT applies the GT predicate on the "brand" field.
func BrandGT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGT(FieldBrand, v))
}

// BrandGTE applies the GTE predicate on the "brand" field.
func BrandGTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGTE(FieldBrand, v))
}

// BrandLT applies the LT predicate on the "brand" field.
func BrandLT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLT(FieldBrand, v))
}

// BrandLTE applies the LTE predicate on the "brand" field.
func BrandLTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLTE(FieldBrand, v))
}

// BrandContains applies the Contains predicate on the "brand" field.
func BrandContains(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContains(FieldBrand, v))
}

// BrandHasPrefix applies the HasPrefix predicate on the "brand" field.
func BrandHasPrefix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasPrefix(FieldBrand, v))
}

// BrandHasSuffix applies the HasSuffix predicate on the "brand" field.
func BrandHasSuffix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasSuffix(FieldBrand, v))
}

// BrandEqualFold applies the EqualFold predicate on the "brand" field.
func BrandEqualFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEqualFold(FieldBrand, v))
}

// BrandContainsFold applies the ContainsFold predicate on the "brand" field.
func BrandContainsFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContainsFold(FieldBrand, v))
}

// LastFourEQ applies the EQ predicate on the "last_four" field.
func LastFourEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldLastFour, v))
}

// LastFourNEQ applies the NEQ predicate on the "last_four" field.
func LastFourNEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNEQ(FieldLastFour, v))
}

// LastFourIn applies the In predicate on the "last_four" field.
func LastFourIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldIn(FieldLastFour, vs...))
}

// LastFourNotIn applies the NotIn predicate on the "last_four" field.
func LastFourNotIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNotIn(FieldLastFour, vs...))
}

// LastFourGT applies the GT predicate on the "last_four" field.
func LastFourGT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGT(FieldLastFour, v))
}

// LastFourGTE applies the GTE predicate on the "last_four" field.
func LastFourGTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGTE(FieldLastFour, v))
}

// LastFourLT applies the LT predicate on the "last_four" field.
func LastFourLT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLT(FieldLastFour, v))
}

// LastFourLTE applies the LTE predicate on the "last_four" field.
func LastFourLTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLTE(FieldLastFour, v))
}

// LastFourContains applies the Contains predicate on the "last_four" field.
func LastFourContains(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContains(FieldLastFour, v))
}

// LastFourHasPrefix applies the HasPrefix predicate on the "last_four" field.
func LastFourHasPrefix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasPrefix(FieldLastFour, v))
}

// LastFourHasSuffix applies the HasSuffix predicate on the "last_four" field.
func LastFourHasSuffix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasSuffix(FieldLastFour, v))
}

// LastFourEqualFold applies the EqualFold predicate on the "last_four" field.
func LastFourEqualFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEqualFold(FieldLastFour, v))
}

// LastFourContainsFold applies the ContainsFold predicate on the "last_four" field.
func LastFourContainsFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContainsFold(FieldLastFour, v))
}

// CardholderNameEQ applies the EQ predicate on the "cardholder_name" field.
func CardholderNameEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldCardholderName, v))
}

// CardholderNameNEQ applies the NEQ predicate on the "cardholder_name" field.
func CardholderNameNEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNEQ(FieldCardholderName, v))
}

// CardholderNameIn applies the In predicate on the "cardholder_name" field.
func CardholderNameIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldIn(FieldCardholderName, vs...))
}

// CardholderNameNotIn applies the NotIn predicate on the "cardholder_name" field.
func CardholderNameNotIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNotIn(FieldCardholderName, vs...))
}

// CardholderNameGT applies the GT predicate on the "cardholder_name" field.
func CardholderNameGT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGT(FieldCardholderName, v))
}

// CardholderNameGTE applies the GTE predicate on the "cardholder_name" field.
func CardholderNameGTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGTE(FieldCardholderName, v))
}

// CardholderNameLT applies the LT predicate on the "cardholder_name" field.
func CardholderNameLT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLT(FieldCardholderName, v))
}

// CardholderNameLTE applies the LTE predicate on the "cardholder_name" field.
func CardholderNameLTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLTE(FieldCardholderName, v))
}

// CardholderNameContains applies the Contains predicate on the "cardholder_name" field.
func CardholderNameContains(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContains(FieldCardholderName, v))
}

// CardholderNameHasPrefix applies the HasPrefix predicate on the "cardholder_name" field.
func CardholderNameHasPrefix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasPrefix(FieldCardholderName, v))
}

// CardholderNameHasSuffix applies the HasSuffix predicate on the "cardholder_name" field.
func CardholderNameHasSuffix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasSuffix(FieldCardholderName, v))
}

// CardholderNameEqualFold applies the EqualFold predicate on the "cardholder_name" field.
func CardholderNameEqualFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEqualFold(FieldCardholderName, v))
}

// CardholderNameContainsFold applies the ContainsFold predicate on the "cardholder_name" field.
func CardholderNameContainsFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContainsFold(FieldCardholderName, v))
}

// BillingZipEQ applies the EQ predicate on the "billing_zip" field.
func BillingZipEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEQ(FieldBillingZip, v))
}

// BillingZipNEQ applies the NEQ predicate on the "billing_zip" field.
func BillingZipNEQ(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNEQ(FieldBillingZip, v))
}

// BillingZipIn applies the In predicate on the "billing_zip" field.
func BillingZipIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldIn(FieldBillingZip, vs...))
}

// BillingZipNotIn applies the NotIn predicate on the "billing_zip" field.
func BillingZipNotIn(vs ...string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldNotIn(FieldBillingZip, vs...))
}

// BillingZipGT applies the GT predicate on the "billing_zip" field.
func BillingZipGT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGT(FieldBillingZip, v))
}

// BillingZipGTE applies the GTE predicate on the "billing_zip" field.
func BillingZipGTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldGTE(FieldBillingZip, v))
}

// BillingZipLT applies the LT predicate on the "billing_zip" field.
func BillingZipLT(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLT(FieldBillingZip, v))
}

// BillingZipLTE applies the LTE predicate on the "billing_zip" field.
func BillingZipLTE(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldLTE(FieldBillingZip, v))
}

// BillingZipContains applies the Contains predicate on the "billing_zip" field.
func BillingZipContains(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContains(FieldBillingZip, v))
}

// BillingZipHasPrefix applies the HasPrefix predicate on the "billing_zip" field.
func BillingZipHasPrefix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasPrefix(FieldBillingZip, v))
}

// BillingZipHasSuffix applies the HasSuffix predicate on the "billing_zip" field.
func BillingZipHasSuffix(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldHasSuffix(FieldBillingZip, v))
}

// BillingZipEqualFold applies the EqualFold predicate on the "billing_zip" field.
func BillingZipEqualFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldEqualFold(FieldBillingZip, v))
}

// BillingZipContainsFold applies the ContainsFold predicate on the "billing_zip" field.
func BillingZipContainsFold(v string) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.FieldContainsFold(FieldBillingZip, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.PaymentMethod {
	return predicate.PaymentMethod(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.PaymentMethod {
	return predicate.PaymentMethod(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentMethod) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentMethod) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentMethod) predicate.PaymentMethod {
	return predicate.PaymentMethod(sql.NotPredicates(p))
}
