// Code generated by hand (no entc extension). DO NOT EDIT.
package ent

import "github.com/k0in/entcrypt"

func init() {
	// Manually register encrypted fields discovered from schema annotations.
	// When using the entcrypt.Extension{} with entc.Generate(), this file
	// is emitted automatically. Without it, you must keep this list in sync
	// with your schema by hand.
	entcrypt.Register("User", "email", "ssn")
}